/// Flutter icons VegetablesIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  VegetablesIcon
///      fonts:
///       - asset: fonts/VegetablesIcon.ttf
///
///
import 'package:flutter/widgets.dart';

class VegetablesIcon {
  VegetablesIcon._();

  static const _kFontFam = 'VegetablesIcon';

  static const IconData mustard = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData ketchup = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData meat = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData bread = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData tomato = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData cabbage = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData carrot = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData recolte = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData chicken = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData ginger = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData cheese = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData onion = IconData(0xe80b, fontFamily: _kFontFam);
}
